name: ceyiz_diz
description: Çeyiz yönetim uygulaması
publish_to: 'none'
version: 1.0.19+26

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.7
  firebase_app_check: ^0.3.2+10
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.2
  
  # UI & Navigation
  go_router: ^14.6.2
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  
  # Utilities
  image_picker: ^1.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  excel: ^4.0.6
  share_plus: ^10.1.3
  path_provider: ^2.1.5
  
  # UI Components
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Use the existing app icons as in-app image assets
    - web/icons/

flutter_launcher_icons:
  android: true
  ios: false
  web:
    generate: true
    image_path: "web/icons/Icon-512.png"
    background_color: "#111418"
    theme_color: "#2563EB"
  image_path: "web/icons/Icon-512.png"
  adaptive_icon_background: "#111418" # fallback background for adaptive icon
  adaptive_icon_foreground: "web/icons/Icon-192.png"
