name: ceyiz_diz
description: Çeyiz yönetim uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.7
  firebase_app_check: ^0.3.2+10
  
  # State Management
  provider: ^6.1.2
  
  # UI & Navigation
  go_router: ^14.6.2
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.1
  
  # Utilities
  image_picker: ^1.1.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  url_launcher: ^6.3.1
  
  # UI Components
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
